# Navigation Function (navigation path)
NavfnROS:
  # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  allow_unknown: true
  # A tolerance on the goal point for the planner.
  default_tolerance: 0.1

# Plans robot movement
TrajectoryPlannerROS:
  max_vel_x: 2.0
  min_vel_x: 0.01
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.3

  acc_lim_theta: 2.0
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  # Defaults to 5.0, lowering it fixes the in-place rotation when at the NavGoal
  # Reference: https://answers.ros.org/question/9795/tuning-navigation-robot-keeps-rotating-when-close-to-its-goal/
  sim_time: 1.0

  # Cybertruck is not Holonomic
  holonomic_robot: false

  # Sets distances in cost function to meters instead of cells (allows different map resolutions)
  meter_scoring: true
